language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" 
script: yarn start 
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN -e REACT_APP_ACCESS_TOKEN=$REACT_APP_ACCESS_TOKEN
    skip_cleanup: true
    on:
      master: true